/** Permission keys used across admin UI (matches frontend Permission interface). */
export const PERMISSION_KEYS = [
  "viewDashboard",
  "viewGrievances",
  "createGrievance",
  "updateGrievanceStatus",
  "deleteGrievance",
  "escalateGrievance",
  "reassignOfficer",
  "viewCaseTypes",
  "manageCaseTypes",
  "viewCategories",
  "manageCategories",
  "viewStations",
  "manageStations",
  "viewQRCodes",
  "manageQRCodes",
  "viewOfficers",
  "manageOfficers",
  "viewEscalations",
  "resolveEscalations",
  "viewReports",
  "exportReports",
  "viewSettings",
  "manageSettings",
  "manageRoles",
  "loginAsVeteran",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];
export type PermissionMap = Record<PermissionKey, boolean>;

export type RbacRole =
  | "super_admin"
  | "area"
  | "headquarter"
  | "station_hq"
  | "user";

/** Roles shown in Settings matrix. */
export const SETTINGS_ROLES: RbacRole[] = [
  "super_admin",
  "area",
  "headquarter",
  "station_hq",
];

/** Default role permissions (from current production localStorage config). */
export const DEFAULT_ROLE_PERMISSIONS: Record<RbacRole, PermissionMap> = {
  super_admin: {
    viewDashboard: true,
    viewGrievances: true,
    createGrievance: true,
    updateGrievanceStatus: true,
    deleteGrievance: true,
    escalateGrievance: true,
    reassignOfficer: true,
    viewCaseTypes: true,
    manageCaseTypes: true,
    viewCategories: true,
    manageCategories: true,
    viewStations: true,
    manageStations: true,
    viewQRCodes: true,
    manageQRCodes: true,
    viewOfficers: true,
    manageOfficers: true,
    viewEscalations: true,
    resolveEscalations: true,
    viewReports: true,
    exportReports: true,
    viewSettings: true,
    manageSettings: true,
    manageRoles: true,
    loginAsVeteran: false,
  },
  area: {
    viewDashboard: true,
    viewGrievances: true,
    createGrievance: true,
    updateGrievanceStatus: true,
    deleteGrievance: false,
    escalateGrievance: true,
    reassignOfficer: true,
    viewCaseTypes: true,
    manageCaseTypes: false,
    viewCategories: true,
    manageCategories: false,
    viewStations: true,
    manageStations: true,
    viewQRCodes: true,
    manageQRCodes: false,
    viewOfficers: true,
    manageOfficers: false,
    viewEscalations: true,
    resolveEscalations: true,
    viewReports: true,
    exportReports: true,
    viewSettings: true,
    manageSettings: false,
    manageRoles: false,
    loginAsVeteran: true,
  },
  headquarter: {
    viewDashboard: true,
    viewGrievances: true,
    createGrievance: true,
    updateGrievanceStatus: true,
    deleteGrievance: false,
    escalateGrievance: true,
    reassignOfficer: false,
    viewCaseTypes: true,
    manageCaseTypes: false,
    viewCategories: true,
    manageCategories: false,
    viewStations: false,
    manageStations: false,
    viewQRCodes: true,
    manageQRCodes: false,
    viewOfficers: false,
    manageOfficers: false,
    viewEscalations: false,
    resolveEscalations: false,
    viewReports: false,
    exportReports: false,
    viewSettings: false,
    manageSettings: false,
    manageRoles: false,
    loginAsVeteran: true,
  },
  station_hq: {
    viewDashboard: true,
    viewGrievances: true,
    createGrievance: false,
    updateGrievanceStatus: false,
    deleteGrievance: false,
    escalateGrievance: false,
    reassignOfficer: false,
    viewCaseTypes: true,
    manageCaseTypes: false,
    viewCategories: true,
    manageCategories: false,
    viewStations: false,
    manageStations: false,
    viewQRCodes: false,
    manageQRCodes: false,
    viewOfficers: false,
    manageOfficers: false,
    viewEscalations: false,
    resolveEscalations: false,
    viewReports: true,
    exportReports: true,
    viewSettings: false,
    manageSettings: false,
    manageRoles: false,
    loginAsVeteran: true,
  },
  user: {
    viewDashboard: false,
    viewGrievances: true,
    createGrievance: true,
    updateGrievanceStatus: false,
    deleteGrievance: false,
    escalateGrievance: false,
    reassignOfficer: false,
    viewCaseTypes: false,
    manageCaseTypes: false,
    viewCategories: false,
    manageCategories: false,
    viewStations: false,
    manageStations: false,
    viewQRCodes: false,
    manageQRCodes: false,
    viewOfficers: false,
    manageOfficers: false,
    viewEscalations: false,
    resolveEscalations: false,
    viewReports: false,
    exportReports: false,
    viewSettings: false,
    manageSettings: false,
    manageRoles: false,
    loginAsVeteran: false,
  },
};

/** Map officer job title → RBAC role template key. */
export const OFFICER_ROLE_TO_RBAC: Record<string, RbacRole> = {
  "Area Officer": "area",
  "Headquarter Officer": "headquarter",
  "Station HQ Officer": "station_hq",
};

export const permissionSchemaFields = Object.fromEntries(
  PERMISSION_KEYS.map((k) => [k, { type: Boolean, default: false }])
);
